name: Update NOC JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 2"  # weekly Tue 03:17 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Debug: show where we are and that scripts/ exists
      - run: |
          pwd
          git rev-parse HEAD
          ls -la
          ls -la scripts || true

      - run: node scripts/fetch_noc.mjs
      - run: node scripts/fetch_ircc_categories.mjs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(noc): update NOC & category JSON (auto)"
          branch: bot/noc-update
          title: "chore(noc): Update NOC & categories JSON"
          body: "Automated NOC data refresh."
          labels: |
            automated
            rules
