name: Update Rules JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 */6 * * *"   # every 6 hours at :17

permissions:
  contents: write

concurrency:
  group: update-rules
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Update rounds (IRCC)
        run: node scripts/update-rounds.mjs

      - name: Update fees (IRCC)
        run: node scripts/update-fees.mjs

      - name: Commit changes (if any)
        run: |
          if git diff --quiet --exit-code; then
            echo "No changes."
            exit 0
          fi
          git config user.name "maplesteps-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/rounds.remote.json data/fees.remote.json
          git commit -m "auto: refresh rounds.remote.json"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
