name: Update NOC & Categories

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # daily 03:00 UTC

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: rules-sync
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=2048
      # Optional: set these repo Secrets if/when you wire real endpoints
      
      NOC_SOURCE_FORMAT: ${{ secrets.NOC_SOURCE_FORMAT }}   # "csv" | "json" | "auto"
      IRCC_CATEGORIES_URL: ${{ secrets.IRCC_CATEGORIES_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # --- BEFORE: capture current URL for comparison ---
      - name: Capture current NOC CSV URL (before sync)
        id: old_noc_url
        shell: bash
        run: |
          set -e
          if [ -f data/noc.2021.json ]; then
            OLD_URL="$(node -e "const fs=require('fs');const p='data/noc.2021.json';try{const d=JSON.parse(fs.readFileSync(p,'utf8'));process.stdout.write(d?.source?.url||'')}catch(e){process.stdout.write('')}")"
          else
            OLD_URL=""
          fi
          echo "url=$OLD_URL" >> "$GITHUB_OUTPUT"
          echo "OLD_URL=$OLD_URL"

      - name: Sync NOC & categories
        run: npm run sync:all

      - name: Validate JSON
        run: node scripts/validate_noc.mjs

      # --- AFTER: capture new URL and compare ---
      - name: Capture new NOC CSV URL (after sync)
        id: new_noc_url
        shell: bash
        run: |
          set -e
          NEW_URL="$(node -e "const fs=require('fs');const p='data/noc.2021.json';try{const d=JSON.parse(fs.readFileSync(p,'utf8'));process.stdout.write(d?.source?.url||'')}catch(e){process.stdout.write('')}")"
          echo "url=$NEW_URL" >> "$GITHUB_OUTPUT"
          echo "NEW_URL=$NEW_URL"

      - name: Open Issue if NOC CSV URL changed
        if: ${{ steps.old_noc_url.outputs.url != '' && steps.new_noc_url.outputs.url != '' && steps.old_noc_url.outputs.url != steps.new_noc_url.outputs.url }}
        uses: actions/github-script@v7
        with:
          script: |
            const oldUrl = '${{ steps.old_noc_url.outputs.url }}';
            const newUrl = '${{ steps.new_noc_url.outputs.url }}';
            const title = 'NOC CSV URL changed';
            const body = [
              'The source CSV URL for NOC 2021 changed.',
              '',
              `**Old:** ${oldUrl}`,
              `**New:** ${newUrl}`,
              '',
              `Run: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`,
              `Date (UTC): ${new Date().toISOString()}`
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              labels: ['automated','rules','noc'],
              body
            });

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "sync(noc): update NOC & categories JSON (auto)"
          branch: bot/noc-update
          title: "sync(noc): Update NOC & categories JSON"
          body: "Automated refresh for NOC + categories."
          add-paths: |
            data/noc.2021.json
            data/noc.categories.json
          labels: |
            automated
            rules
